// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddToQueue(arg1:string,arg2:string):Promise<main.AddResult>;

export function AppVersion():Promise<string>;

export function CanInstallFfmpeg():Promise<boolean>;

export function CancelDownload(arg1:string):Promise<void>;

export function CheckFfmpeg():Promise<boolean>;

export function CheckYtDlp():Promise<boolean>;

export function FetchPlaylist(arg1:string):Promise<Array<main.PlaylistEntry>>;

export function FfmpegInstallHint():Promise<string>;

export function GetDefaultDir():Promise<string>;

export function GetMaxConcurrent():Promise<number>;

export function GetYtDlpVersion():Promise<string>;

export function InstallFfmpeg():Promise<void>;

export function InstallYtDlp():Promise<void>;

export function IsM3U8URL(arg1:string):Promise<boolean>;

export function PauseDownload(arg1:string):Promise<void>;

export function ResumeDownload(arg1:string):Promise<void>;

export function RetryDownload(arg1:string):Promise<void>;

export function RetryWithReferer(arg1:string,arg2:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SetMaxConcurrent(arg1:number):Promise<void>;

export function StartDownload(arg1:string):Promise<void>;

export function UpdateYtDlp():Promise<void>;

export function YtDlpUpdateImpact():Promise<main.UpdateImpact>;
