// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToQueue(arg1:string,arg2:string):Promise<string>;

export function CancelDownload(arg1:string):Promise<void>;

export function CheckFfmpeg():Promise<boolean>;

export function CheckYtDlp():Promise<boolean>;

export function FfmpegInstallHint():Promise<string>;

export function GetDefaultDir():Promise<string>;

export function InstallYtDlp():Promise<void>;

export function SelectDirectory():Promise<string>;
