// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToQueue(arg1, arg2) {
  return window['go']['main']['App']['AddToQueue'](arg1, arg2);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CheckFfmpeg() {
  return window['go']['main']['App']['CheckFfmpeg']();
}

export function CheckYtDlp() {
  return window['go']['main']['App']['CheckYtDlp']();
}

export function FetchPlaylist(arg1) {
  return window['go']['main']['App']['FetchPlaylist'](arg1);
}

export function FfmpegInstallHint() {
  return window['go']['main']['App']['FfmpegInstallHint']();
}

export function GetDefaultDir() {
  return window['go']['main']['App']['GetDefaultDir']();
}

export function InstallYtDlp() {
  return window['go']['main']['App']['InstallYtDlp']();
}

export function PauseDownload(arg1) {
  return window['go']['main']['App']['PauseDownload'](arg1);
}

export function ResumeDownload(arg1) {
  return window['go']['main']['App']['ResumeDownload'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}
